import type { Metadata } from "next";
import "./globals.css";
import "../../envConfig.ts";
import { NavBar } from "@/components";
import { Toaster } from "react-hot-toast";
import { getCurrentUserData } from "@/lib";

export const metadata: Metadata = {
    title: "Sajilo Vote",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getCurrentUserData();
    return (
        <html lang="en" className="">
            <body className={`antialiased`}>
                <NavBar user={user} />
                <main className="lg:ml-64 p-4 min-h-screen">{children}</main>
                <Toaster position="top-right" />
            </body>
        </html>
    );
}
