import type { Metadata } from "next";
import "./globals.css";
import NavSideBar from "@/components/NavSideBar";

export const metadata: Metadata = {
    title: "Who Wins",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <NavSideBar />
                {children}
            </body>
        </html>
    );
}
